// <auto-generated />
namespace Simple02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deleteEnqPos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteEnqPos));
        
        string IMigrationMetadata.Id
        {
            get { return "201611290308268_deleteEnqPos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
