// <auto-generated />
namespace Simple02.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DeletePostVoterRelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DeletePostVoterRelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201702090343527_DeletePostVoterRelation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
